
# Makefile to run specific tests

loopback:
	python -m unittest net-app-tester.Loopback

priority_mix:
	python -m unittest net-app-tester.PriorityMix

old_tester_loopback:
	python -m unittest old_tester.Loopback

parallel_loopback:
	python -m unittest old_tester.ParallelLoopback

stream:
	python -m unittest net-app-tester.Stream

nn_inference:
	python -m unittest net-app-tester.NNInference

othello:
	python -m unittest net-app-tester.OthelloTest

multithread:
	python -m unittest net-app-tester.Multithread

