
# Makefile to run specific tests

loopback:
	python -m unittest net-app-tester.Loopback

stream:
	python -m unittest net-app-tester.Stream

nn_inference:
	python -m unittest net-app-tester.NNInference

othello:
	python -m unittest net-app-tester.OthelloTest

