
# Makefile to run specific tests

loopback:
	python -m unittest net-app-tester.Loopback

throughput:
	python -m unittest net-app-tester.ThroughputTest

scheduler_test:
	python -m unittest net-app-tester.SchedulerTest

priority_mix:
	python -m unittest net-app-tester.PriorityMix

var_duration:
	python -m unittest net-app-tester.PriorityVaryDuration

parallel_loopback:
	python -m unittest net-app-tester.ParallelLoopback

stream:
	python -m unittest net-app-tester.Stream

nn_inference:
	python -m unittest net-app-tester.NNInference

othello:
	python -m unittest net-app-tester.OthelloTest

nbody:
	python -m unittest net-app-tester.NBodyTest

multithread:
	python -m unittest net-app-tester.Multithread

